spring:
  datasource:
    username: 'devuser'
    password: 'Password1234!'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/demodb'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    open-in-view: true
